//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AnswerID { get; set; }
        public int FKIDTheme { get; set; }
        public string Name { get; set; }
        public int CountVoice { get; set; }
        public int Sort { get; set; }
        public bool IsVisible { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
    
        public virtual VoiceTheme VoiceTheme { get; set; }
    }
}
