//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class BottomMenu
    {
        public int MenuItemID { get; set; }
        public Nullable<int> MenuItemParentID { get; set; }
        public string MenuItemName { get; set; }
        public int MenuItemUrlType { get; set; }
        public string MenuItemUrlPath { get; set; }
        public string MenuItemIcon { get; set; }
        public int ShowMode { get; set; }
        public int SortOrder { get; set; }
        public bool Enabled { get; set; }
        public bool Blank { get; set; }
        public bool NoFollow { get; set; }
    }
}
