//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public string BrandDescription { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string UrlPath { get; set; }
        public string BrandBriefDescription { get; set; }
        public string BrandSiteUrl { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
