//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public Certificate()
        {
            this.CustomerCertificates = new HashSet<CustomerCertificate>();
        }
    
        public int CertificateID { get; set; }
        public string CertificateCode { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string FromName { get; set; }
        public string ToName { get; set; }
        public double Sum { get; set; }
        public string Message { get; set; }
        public bool Used { get; set; }
        public bool Enable { get; set; }
        public string ToEmail { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ApplyOrderNumber { get; set; }
    
        public virtual ICollection<CustomerCertificate> CustomerCertificates { get; set; }
        public virtual Certificate Certificate1 { get; set; }
        public virtual Certificate Certificate2 { get; set; }
        public virtual Order Order { get; set; }
    }
}
