//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.ShippingMethods = new HashSet<ShippingMethod>();
        }
    
        public int CityID { get; set; }
        public int RegionID { get; set; }
        public string CityName { get; set; }
        public int CitySort { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<ShippingMethod> ShippingMethods { get; set; }
    }
}
