//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public Color()
        {
            this.Offers = new HashSet<Offer>();
            this.Photos = new HashSet<Photo>();
        }
    
        public int ColorID { get; set; }
        public string ColorName { get; set; }
        public string ColorCode { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
