//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public System.Guid ContactID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Zone { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> RegionID { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Region Region { get; set; }
    }
}
