//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_en
    {
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryISO2 { get; set; }
        public string CountryISO3 { get; set; }
    }
}
