//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.CustomerCoupons = new HashSet<CustomerCoupon>();
            this.Categories = new HashSet<Category>();
            this.Customers = new HashSet<Customer>();
            this.Products = new HashSet<Product>();
        }
    
        public int CouponID { get; set; }
        public string Code { get; set; }
        public int Type { get; set; }
        public double Value { get; set; }
        public System.DateTime AddingDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public int PossibleUses { get; set; }
        public int ActualUses { get; set; }
        public bool Enabled { get; set; }
        public Nullable<decimal> MinimalOrderPrice { get; set; }
    
        public virtual ICollection<CustomerCoupon> CustomerCoupons { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
