//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int CurrencyID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public double CurrencyValue { get; set; }
        public string CurrencyIso3 { get; set; }
        public bool IsCodeBefore { get; set; }
        public string PriceFormat { get; set; }
        public Nullable<int> CurrencyNumIso3 { get; set; }
    }
}
