//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Contacts = new HashSet<Contact>();
            this.CustomerRoleActions = new HashSet<CustomerRoleAction>();
            this.OpenIdLinkCustomers = new HashSet<OpenIdLinkCustomer>();
            this.Coupons = new HashSet<Coupon>();
        }
    
        public System.Guid CustomerID { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public System.DateTime RegistrationDateTime { get; set; }
        public Nullable<bool> Subscribed4News { get; set; }
        public string Email { get; set; }
        public Nullable<int> CustomerGroupId { get; set; }
        public Nullable<int> CustomerRole { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual CustomerGroup CustomerGroup { get; set; }
        public virtual ICollection<CustomerRoleAction> CustomerRoleActions { get; set; }
        public virtual ICollection<OpenIdLinkCustomer> OpenIdLinkCustomers { get; set; }
        public virtual ICollection<Coupon> Coupons { get; set; }
    }
}
