//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportFeedHistory
    {
        public int id { get; set; }
        public string moduleName { get; set; }
        public string filePath { get; set; }
        public string fileLink { get; set; }
        public int fileSize { get; set; }
        public System.DateTime date { get; set; }
    }
}
