//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportFeedSelectedCategory
    {
        public string ModuleName { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
