//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLibrary
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemParentID { get; set; }
        public string ItemIcon { get; set; }
        public int ItemType { get; set; }
        public string filePath { get; set; }
        public bool Enabled { get; set; }
        public int SortOrder { get; set; }
    }
}
