//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoIP
    {
        public int ID { get; set; }
        public long begin_num { get; set; }
        public long end_num { get; set; }
        public string country_code { get; set; }
        public string country_name { get; set; }
    }
}
