//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailFormatType
    {
        public int MailFormatTypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Comment { get; set; }
    }
}
