//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailFormat
    {
        public int MailFormatID { get; set; }
        public string FormatName { get; set; }
        public string FormatText { get; set; }
        public int FormatType { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool Enable { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
