//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageLog
    {
        public int ID { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Title { get; set; }
        public string MessageText { get; set; }
    }
}
