//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public int NewsCategoryID { get; set; }
        public string Title { get; set; }
        public string TextToPublication { get; set; }
        public string TextToEmail { get; set; }
        public string TextAnnotation { get; set; }
        public bool ShowOnMainPage { get; set; }
        public System.DateTime AddingDate { get; set; }
        public string UrlPath { get; set; }
    
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
