//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCategory
    {
        public NewsCategory()
        {
            this.News = new HashSet<News>();
        }
    
        public int NewsCategoryID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string UrlPath { get; set; }
    
        public virtual ICollection<News> News { get; set; }
    }
}
