//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public Offer()
        {
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public int OfferID { get; set; }
        public int ProductID { get; set; }
        public double Amount { get; set; }
        public double Price { get; set; }
        public double SupplyPrice { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public string ArtNo { get; set; }
        public bool Main { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }

        public Offer Edit(Offer item)
        {
            this.Amount = item.Amount;
            this.Price = item.Price;

            return this;
        }
        public Offer Empty()
        {
            this.Amount = 0;

            return this;
        }
    }
}
