//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineClientInfo
    {
        public string sessionID { get; set; }
        public string Address { get; set; }
        public string UserAgentBrowser { get; set; }
        public string LastAccessedPath { get; set; }
        public System.DateTime Started { get; set; }
        public string UserAgentOS { get; set; }
        public string CountryByGeoIp { get; set; }
    }
}
