//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Certificates = new HashSet<Certificate>();
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderPaymentInfoes = new HashSet<OrderPaymentInfo>();
            this.OrderTaxes = new HashSet<OrderTax>();
        }
    
        public int OrderID { get; set; }
        public string Number { get; set; }
        public Nullable<int> ShippingMethodID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<int> AffiliateID { get; set; }
        public Nullable<double> OrderDiscount { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string GroupName { get; set; }
        public Nullable<double> GroupDiscount { get; set; }
        public string CustomerComment { get; set; }
        public string StatusComment { get; set; }
        public string AdditionalTechInfo { get; set; }
        public string AdminOrderComment { get; set; }
        public bool Decremented { get; set; }
        public double ShippingCost { get; set; }
        public double TaxCost { get; set; }
        public double SupplyTotal { get; set; }
        public double Sum { get; set; }
        public int OrderStatusID { get; set; }
        public int ShippingContactID { get; set; }
        public int BillingContactID { get; set; }
        public string PaymentMethodName { get; set; }
        public string ShippingMethodName { get; set; }
        public string CertificateCode { get; set; }
        public Nullable<double> CertificatePrice { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> CouponType { get; set; }
        public Nullable<double> CouponValue { get; set; }
        public Nullable<decimal> PaymentCost { get; set; }
    
        public virtual ICollection<Certificate> Certificates { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ShippingMethod ShippingMethod { get; set; }
        public virtual OrderCurrency OrderCurrency { get; set; }
        public virtual OrderCustomer OrderCustomer { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<OrderPaymentInfo> OrderPaymentInfoes { get; set; }
        public virtual OrderPickPoint OrderPickPoint { get; set; }
        public virtual ICollection<OrderTax> OrderTaxes { get; set; }
        public virtual PaymentDetail PaymentDetail { get; set; }
    }
}
