//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderCustomOptions = new HashSet<OrderCustomOption>();
        }
    
        public int OrderItemID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public double Amount { get; set; }
        public string ArtNo { get; set; }
        public double SupplyPrice { get; set; }
        public double Weight { get; set; }
        public bool IsCouponApplied { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public double DecrementedAmount { get; set; }
        public Nullable<int> PhotoID { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderCustomOption> OrderCustomOptions { get; set; }
    }
}
