//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderByRequest
    {
        public int OrderByRequestId { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ArtNo { get; set; }
        public int Quantity { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Comment { get; set; }
        public bool IsComplete { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CodeCreateDate { get; set; }
        public Nullable<int> OfferID { get; set; }
    }
}
