//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.Orders = new HashSet<Order>();
            this.OrderPaymentInfoes = new HashSet<OrderPaymentInfo>();
            this.PaymentParams = new HashSet<PaymentParam>();
            this.Cities = new HashSet<City>();
            this.Countries = new HashSet<Country>();
            this.ShippingMethods = new HashSet<ShippingMethod>();
        }
    
        public int PaymentMethodID { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public int SortOrder { get; set; }
        public string Description { get; set; }
        public int PaymentType { get; set; }
        public string IconFileName { get; set; }
        public Nullable<decimal> Extracharge { get; set; }
        public Nullable<int> ExtrachargeType { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual GiftCertificatePayment GiftCertificatePayment { get; set; }
        public virtual ICollection<OrderPaymentInfo> OrderPaymentInfoes { get; set; }
        public virtual ICollection<PaymentParam> PaymentParams { get; set; }
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<ShippingMethod> ShippingMethods { get; set; }
    }
}
