//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitPlan
    {
        public int PlanID { get; set; }
        public int SalesPlan { get; set; }
        public double ProfitPlan1 { get; set; }
        public System.DateTime Date { get; set; }
    }
}
