//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranx
    {
        public int RangeID { get; set; }
        public double Bound { get; set; }
        public decimal Value { get; set; }
        public int Type { get; set; }
    }
}
