//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Cities = new HashSet<City>();
            this.Contacts = new HashSet<Contact>();
        }
    
        public int RegionID { get; set; }
        public int CountryID { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public Nullable<int> RegionSort { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
