//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAction
    {
        public int RoleActionID { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
        public bool Enabled { get; set; }
        public string Category { get; set; }
        public int SortOrder { get; set; }
    }
}
