//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchStatistic
    {
        public int ID { get; set; }
        public string Request { get; set; }
        public int ResultCount { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string SearchTerm { get; set; }
        public string CustomerID { get; set; }
    }
}
