//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartItemId { get; set; }
        public int ShoppingCartType { get; set; }
        public System.Guid CustomerId { get; set; }
        public int OfferId { get; set; }
        public string AttributesXml { get; set; }
        public double Amount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Offer Offer { get; set; }
    }
}
