//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticPage
    {
        public int StaticPageID { get; set; }
        public string PageName { get; set; }
        public string PageText { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<bool> IndexAtSiteMap { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Comment { get; set; }
        public bool Enabled { get; set; }
        public string UrlPath { get; set; }
    }
}
