//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribe
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public bool Enable { get; set; }
        public string ActivateCode { get; set; }
        public string DectivateCode { get; set; }
        public Nullable<System.DateTime> ActivateDate { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
