//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public Tax()
        {
            this.TaxRegionRates = new HashSet<TaxRegionRate>();
            this.Products = new HashSet<Product>();
            this.Categories = new HashSet<Category>();
        }
    
        public int TaxID { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public int Priority { get; set; }
        public int DependsOnAddress { get; set; }
        public bool ShowInPrice { get; set; }
        public string RegNumber { get; set; }
        public int CountryID { get; set; }
        public int RateType { get; set; }
        public double FederalRate { get; set; }
    
        public virtual GiftCertificateTax GiftCertificateTax { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<TaxRegionRate> TaxRegionRates { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
