//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korea
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoiceTheme
    {
        public VoiceTheme()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int VoiceThemeID { get; set; }
        public int PSYID { get; set; }
        public string Name { get; set; }
        public bool IsHaveNullVoice { get; set; }
        public bool IsDefault { get; set; }
        public bool IsClose { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
