// <auto-generated />
namespace Korea.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class import51 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(import51));
        
        string IMigrationMetadata.Id
        {
            get { return "201503110537046_import51"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
